workflows:
  vegetable-workflow:
    name: TestProject Pipeline
    scripts:
      - name: CICD Started
        script: echo "Welcome to your CICD set up!"
      - name: Build TestProject
        script: xcodebuild build -workspace "TestProjectCI.xcodeproj/project.xcworkspace" -scheme "TestProjectCI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    publishing:
      email:
        recipients:
          - gvladislav_52@mail.ru
